### ISSUE TITLE
UI editor

### ISSUE THREAD

**Issue by PlusMinus0** [mervick/Qt-Creator-Darcula#1]
Unfortunately, the UI editor becomes pretty unusable. The UI-preview itself, as well as object- and property-widget are displayed with a weird mix of colors (see attached screenshot - it's worse for the UI-preview).

![screenshot from 2015-11-09 16 48 01](https://cloud.githubusercontent.com/assets/11473351/11038134/becb4570-8701-11e5-9607-73c6374a20c3.png)

**Comment by mervick** [comment]
Thanks for your feedback!
I'll try to fix it as soon as free time.

**Comment by mervick** [comment]
I corrected some styles and now you can turn off "Color Groups" in the bottom part of property-widget (these colors is hard coded) and it will be looks better.

![selection_025](https://cloud.githubusercontent.com/assets/2429298/11127785/a636a444-897e-11e5-9a00-50e5f6c22f8b.png)
